name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - run: pwd

    - name: Archive build artifacts
      run: |
          # Create a ZIP archive of the build artifacts (change the directory and filenames as needed)
          zip -r build.zip ./out

    - run: ls -a

    - name: Deploy
      run: |
        # Add your deployment steps here
        curl -X POST -F "zip_file=@./build.zip" https://root.ucfashionweek.com/api/uploader.php

