name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Archive build artifacts
      run: zip -j -r build.zip ./out/*

    - name: Deploy
      run: curl -X POST -F "zip_file=@./build.zip" https://root.ucfashionweek.com/api/uploader.php

